name: releasy
description: A lightweight Dart CLI tool to automate version bumping, tagging, and GitHub release creation.
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  yaml: ^3.1.2

executables:
  releasy: bin/releasy.dart